### ISSUE TITLE
way to access ttf 

### ISSUE THREAD

**Issue by ofZach** [braitsch/ofxSmartFont#1]
for a project I found it useful to get access to the underlying ofTrueTypeFont to query it more directly.  What I did is just comment out "private:" but it seems like that's a feature that might be useful to have...

**Comment by braitsch** [comment]
I've been meaning to update ofxSmartFont to extend ofTrueTypeFont and just never got around to it. Now all the ofTrueTypeFont methods should be properly exposed. Thanks for the reminder.
